---
- name: unarchive application.zip
  unarchive:
     src={{ application_zip }}
     dest=/opt
  run_once: true

- name: register (systemd) app service
  template:
      src=template/app.service.j2
      dest=/etc/systemd/system/{{ application_service }}.service
      mode=700

- name: (re)start application service
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ application_service }}"
  tags: deploy
